usage: opensource

integration:
  name: minitest

includes:
  - lib
  - test

requires:
  - ./test/support/mutant_setup.rb

matcher:
  subjects:
    - YARD::Markdown::AnchorComponentHelper#
    - YARD::Markdown::ArefHelper#
    - YARD::Markdown::ObjectListingHelper#
    - YARD::Markdown::TagFormattingHelper#
