name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-slim
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0"
          bundler-cache: true
      - name: yard-lint
        run: bundle exec yard-lint
      - name: Standard Ruby
        run: bundle exec standardrb

  build:
    runs-on: ubuntu-slim
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.4"
          - "4.0"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: test
        run: bundle exec rake test
      - name: validate real-world markdown
        run: bundle exec rake markdown:validate_real_world

  mutant:
    needs: build
    runs-on: ubuntu-slim
    name: Mutant
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0"
          bundler-cache: true
      - name: Run Mutant
        run: |
          git fetch origin main
          bundle exec mutant run --fail-fast --since origin/main
